
/* This file was auto-generated by eo-maven-plugin (1.0-SNAPSHOT b5a4c9a 2023-08-17T12:29:38) on 2023-08-21T15:22:26.634504Z; your changes will be discarded on the next build */
package EOorg.EOeolang;

import org.eolang.AtComposite;
import org.eolang.AtOnce;
import org.eolang.Data;
import org.eolang.Dataized;
import org.eolang.PhCopy;
import org.eolang.PhDefault;
import org.eolang.PhLocated;
import org.eolang.PhMethod;
import org.eolang.PhWith;
import org.eolang.Phi;
import org.eolang.XmirObject;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

// <o abstract="" line="208" loc="Φ.org.eolang.measures-rust-plus" name="measures-rust-plus" original-name="measures-rust-plus" pos="0"> 
//   <o base="org.eolang.int" data="int" line="209" loc="Φ.org.eolang.measures-rust-plus.a" name="a" pos="2">5</o>
//   <o base="org.eolang.int" data="int" line="210" loc="Φ.org.eolang.measures-rust-plus.b" name="b" pos="2">10</o>
//   <o base=".rust" line="211" loc="Φ.org.eolang.measures-rust-plus.plus" name="plus" pos="4"> 
//     <o base=".eolang" line="211" loc="Φ.org.eolang.measures-rust-plus.plus.ρ" pos="2"> 
//       <o base=".org" line="211" loc="Φ.org.eolang.measures-rust-plus.plus.ρ.ρ" pos="2"> 
//         <o base="Q" line="211" loc="Φ.org.eolang.measures-rust-plus.plus.ρ.ρ.ρ" pos="2"/>
//       </o>
//     </o>
//     <o base="org.eolang.string" data="string" line="212" loc="Φ.org.eolang.measures-rust-plus.plus.α0" pos="4">use eo_env::EOEnv;\nuse eo_env::eo_enum::EO;\nuse eo_env::eo_enum::EO::{EOInt};\nuse byteorder::{BigEndian, ReadBytesExt};\n\npub fn foo(env: &mut EOEnv) -> EO {\n  let a = env.find(\"^.a\") as u32;\n  let b = env.find(\"^.b\") as u32;\n  let bytes_a = env.dataize(a).unwrap();\n  let mut arr_a = unsafe { &*(&bytes_a[0..] as *const _  as *const [u8]) };\n\n  let bytes_b = env.dataize(b).unwrap();\n  let mut arr_b = unsafe { &*(&bytes_b[0..] as *const _  as *const [u8]) };\n\n  let a = arr_a.read_i64::<BigEndian>().unwrap();\n  let b = arr_b.read_i64::<BigEndian>().unwrap();\n  //println!(\"sum 5 + 10 = {}\", a + b);\n\n  EOInt(a + b)\n}</o>
//     <o base="org.eolang.tuple" data="tuple" line="234" loc="Φ.org.eolang.measures-rust-plus.plus.α1" pos="4"> 
//       <o base="measures-rust-plus$t2$t2$a0" cut="139" line="235" loc="Φ.org.eolang.measures-rust-plus.plus.α1.α0" pos="6" ref="235"/>
//       <o base="org.eolang.string" data="string" line="236" loc="Φ.org.eolang.measures-rust-plus.plus.α1.α1" pos="6">byteorder:1.4.3</o>
//     </o>
//   </o>
//   <o base="org.eolang.hamcrest.assert-that" line="237" loc="Φ.org.eolang.measures-rust-plus.φ" name="@" pos="2"> 
//     <o base="plus" line="238" loc="Φ.org.eolang.measures-rust-plus.φ.α0" pos="4" ref="211"/>
//     <o base=".equal-to" line="239" loc="Φ.org.eolang.measures-rust-plus.φ.α1" pos="5"> 
//       <o base="$" line="239" loc="Φ.org.eolang.measures-rust-plus.φ.α1.ρ" pos="4"/>
//       <o base="org.eolang.int" data="int" line="239" loc="Φ.org.eolang.measures-rust-plus.φ.α1.α0" pos="15">15</o>
//     </o>
//   </o>
// </o>
@XmirObject(name = "measures-rust-plusTest", oname = "measures-rust-plus", source = "/home/tardis3/eo/eo-runtime/src/test/eo/org/eolang/rust-tests.eo")
public final class EOmeasures_rust_plus_testTest extends PhDefault {
  public EOmeasures_rust_plus_testTest() {
    this.add("a", new AtOnce(new AtComposite(this, rho -> {
      Phi ret = new EOint(Phi.Φ);
        ret = new PhLocated(ret, 209, 2, "Φ.org.eolang.measures-rust-plus.a");
        ret = new PhWith(ret, "Δ", new Data.Value<>(5L));
      return ret;
    })));
    this.add("b", new AtOnce(new AtComposite(this, rho -> {
      Phi ret = new EOint(Phi.Φ);
        ret = new PhLocated(ret, 210, 2, "Φ.org.eolang.measures-rust-plus.b");
        ret = new PhWith(ret, "Δ", new Data.Value<>(10L));
      return ret;
    })));
    this.add("plus", new AtOnce(new AtComposite(this, rho -> {
      Phi ret_base_base_base = Phi.Φ;
        ret_base_base_base = new PhLocated(ret_base_base_base, 211, 2, "Φ.org.eolang.measures-rust-plus.plus.ρ.ρ.ρ");
      Phi ret_base_base = new PhMethod(ret_base_base_base, "org");
        ret_base_base = new PhLocated(ret_base_base, 211, 2, "Φ.org.eolang.measures-rust-plus.plus.ρ.ρ");
      Phi ret_base = new PhMethod(ret_base_base, "eolang");
        ret_base = new PhLocated(ret_base, 211, 2, "Φ.org.eolang.measures-rust-plus.plus.ρ");
      Phi ret = new PhMethod(ret_base, "rust");
        ret = new PhLocated(ret, 211, 4, "Φ.org.eolang.measures-rust-plus.plus");
      ret = new PhCopy(ret);
        Phi ret_1 = new EOstring(Phi.Φ);
          ret_1 = new PhLocated(ret_1, 212, 4, "Φ.org.eolang.measures-rust-plus.plus.α0");
          ret_1 = new PhWith(ret_1, "Δ", new Data.Value<>("use eo_env::EOEnv;\nuse eo_env::eo_enum::EO;\nuse eo_env::eo_enum::EO::{EOInt};\nuse byteorder::{BigEndian, ReadBytesExt};\n\npub fn foo(env: &mut EOEnv) -> EO {\n  let a = env.find(\"^.a\") as u32;\n  let b = env.find(\"^.b\") as u32;\n  let bytes_a = env.dataize(a).unwrap();\n  let mut arr_a = unsafe { &*(&bytes_a[0..] as *const _  as *const [u8]) };\n\n  let bytes_b = env.dataize(b).unwrap();\n  let mut arr_b = unsafe { &*(&bytes_b[0..] as *const _  as *const [u8]) };\n\n  let a = arr_a.read_i64::<BigEndian>().unwrap();\n  let b = arr_b.read_i64::<BigEndian>().unwrap();\n  //println!(\"sum 5 + 10 = {}\", a + b);\n\n  EOInt(a + b)\n}"));
        Phi ret_2 = Phi.Φ.attr("org").get().attr("eolang").get().attr("tuple").get();
          ret_2 = new PhLocated(ret_2, 234, 4, "Φ.org.eolang.measures-rust-plus.plus.α1");
          Phi[] ret_2_a = new Phi[2];
          Phi ret_2_a0 = new EOω1t2$EOt2$EOa0(rho);
            ret_2_a0 = new PhLocated(ret_2_a0, 235, 6, "Φ.org.eolang.measures-rust-plus.plus.α1.α0");
          ret_2_a[0] = ret_2_a0;
          Phi ret_2_a1 = new EOstring(Phi.Φ);
            ret_2_a1 = new PhLocated(ret_2_a1, 236, 6, "Φ.org.eolang.measures-rust-plus.plus.α1.α1");
            ret_2_a1 = new PhWith(ret_2_a1, "Δ", new Data.Value<>("byteorder:1.4.3"));
          ret_2_a[1] = ret_2_a1;
          ret_2 = new PhWith(new PhCopy(ret_2), "Δ", new Data.Value<Phi[]>(ret_2_a));
        ret = new PhWith(ret, 0, ret_1);
        ret = new PhWith(ret, 1, ret_2);
      return ret;
    })));
    this.add("φ", new AtOnce(new AtComposite(this, rho -> {
      Phi ret = Phi.Φ.attr("org").get().attr("eolang").get().attr("hamcrest").get().attr("assert-that").get();
        ret = new PhLocated(ret, 237, 2, "Φ.org.eolang.measures-rust-plus.φ");
      ret = new PhCopy(ret);
        Phi ret_1 = new PhMethod(rho, "plus");
          ret_1 = new PhLocated(ret_1, 238, 4, "Φ.org.eolang.measures-rust-plus.φ.α0");
        Phi ret_2_base = rho;
          ret_2_base = new PhLocated(ret_2_base, 239, 4, "Φ.org.eolang.measures-rust-plus.φ.α1.ρ");
        Phi ret_2 = new PhMethod(ret_2_base, "equal-to");
          ret_2 = new PhLocated(ret_2, 239, 5, "Φ.org.eolang.measures-rust-plus.φ.α1");
        ret_2 = new PhCopy(ret_2);
          Phi ret_2_1 = new EOint(Phi.Φ);
            ret_2_1 = new PhLocated(ret_2_1, 239, 15, "Φ.org.eolang.measures-rust-plus.φ.α1.α0");
            ret_2_1 = new PhWith(ret_2_1, "Δ", new Data.Value<>(15L));
          ret_2 = new PhWith(ret_2, 0, ret_2_1);
        ret = new PhWith(ret, 0, ret_1);
        ret = new PhWith(ret, 1, ret_2);
      return ret;
    })));
  }

  @Test
  public void works() throws Exception {
    final int count = 1;
    final long start = System.currentTimeMillis();
    for (int i = 0; i < count; i++) {
      new Dataized(new EOmeasures_rust_plusTest()).take();
    }
    final long finish = System.currentTimeMillis();
    System.out.println(((double) finish - start) / count);
    Assertions.assertTrue(true);
  }

  @Test
  // 0.496 ms with jit
  public void full()throws Exception {
    final int warmup = 1000;
    final Dataized full_test = new Dataized(new EOmeasures_rust_plusTest());
    for (int i = 0; i < warmup; i++) {
      full_test.take();
    }
    final int count = 500;
    final long start = System.currentTimeMillis();
    for (int i = 0; i < count; i++) {
      full_test.take();
    }
    final long finish = System.currentTimeMillis();
    System.out.println((0.0 + finish - start) / count);
    Assertions.assertTrue(true);
  }

  @Test
  // 0.41 with jit
  // 10.04 without jit
  public void plus_only() throws Exception {
    final Phi plus = new EOmeasures_rust_plusTest().attr("plus").get();
    final Dataized dataized = new Dataized(plus);
    final int warmup = 500;
    for (int i = 0; i < warmup; i++) {
      dataized.take();
    }
    final int count = 500;
    final long start = System.currentTimeMillis();
    for (int i = 0; i < count; i++) {
      dataized.take();
    }
    final long finish = System.currentTimeMillis();
    System.out.println((0.0 + finish - start) / count);
    Assertions.assertTrue(true);
  }

// <o abstract="" ancestors="1" line="235" loc="Φ.org.eolang.measures-rust-plus$t2$t2$a0" name="measures-rust-plus$t2$t2$a0" parent="measures-rust-plus" pos="6"/>
@XmirObject(name = "ω1t2$t2$a0", oname = "ω1t2$t2$a0", source = "/home/tardis3/eo/eo-runtime/src/test/eo/org/eolang/rust-tests.eo")
public final class EOω1t2$EOt2$EOa0 extends PhDefault {
  public EOω1t2$EOt2$EOa0(final Phi sigma) {
    super(sigma);
  }
}
}
